### ISSUE TITLE
Running code

### ISSUE THREAD

**Issue by LiviaCavalcanti** [tawnkramer/find_body#1]
Hi! Do you have the model weights to make available? Could you share what kind of environment you trained your model for?

**Comment by tawnkramer** [comment]
I didn't succeed in getting a good result w this project. I would recommend checking out posenet if you need something to track the body.
https://www.tensorflow.org/lite/models/pose_estimation/overview

**Comment by LiviaCavalcanti** [comment]
Thank you! I will take a look
